---
title: "README"
author: "WWoelmer"
date: "January 31, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

The dataset I will be using in this class is a historical time series dataset of Beaverdam Reservoir a drinking water reservoir in Vinton, VA. Data has been collected by the Carey Lab on a weekly basis in the summer to a monthly basis during winter months from 2013 to present. Variables include nutrient chemistry (nitrogen, phosphorus, and carbon) at the deep hole of the reservoir; water quality variables including conductivity, specific conductivity, dissolved oxygen, pH, chlorophyll, and water temperature from the surface to the bottom of the reservoir; meteorological variables for the region including shortwave radiation, precipitation, windspeeds, and air temperature. 

-------------
Week 1
R script: Lesson1_Jan24_2019.Rmd
Input data file: FCR_VT_data_2013_2017.csv
Did some basic data manipulations and calculations
----------------------


------------------------
Lesson 2 Jan 31, 2019
R script:Lesson 2 Assignment
Input data file: CTD_Meta_13_17.csv
Created data file: BVR_CTD.csv
Description: create 'bins' of CTD depth profiles, make some basic calculations. This bins were created because the CTD takes super high-frequency measurements, and in order to think about the data more clearly, I've selected the closest measurement to given depths. I think the data is tidy! (??)

-----------------------
Lesson 3 Feb 13, 2019
R script: week3_WWoelmer.R
input data file: BVR_CTD.csv
Description: plotted several visualizations of temperature and chlorophyll data by depths in BVR reservoir

--------------------------
Week 4 Feb 20, 2019
R script: none
Assignment: create a hypothesis about your data and state how you would test it statistically
Submitted on canvas

--------------------------
Week 5, Feb 28, 2019
R script: Week5_StatisticalTests_wwoelmer.R
input data file: BVR_CTD.csv
Description: formed two hypotheses and tested them both using 1) a for loop and 2) pearson's correlation. Hypotheses stated within R script

-------------------------
Week 6, Feb 28, 2019
R script: Week6_distributions_wwoelmer.R
input data file: BVR_CTD.csv
Description: determined the distribution of chlorophyll a, created a pseudo distribution with the same shape and rate, and then asked some questions about the distribution

--------------------------
Week 7 & 8, Apr 3, 2019
R Script: Week8_LinearModels_wwoelmer.R
input data file: BVR_CTD.csv
Description: 
Part1-developed a univariate linear model between chlorophyll-a and water temperature,
chl-a is not normally distributed so log-transformed first, still not a great linear model!
Part 2-developed an additive and interactive model of chlorophyll-a and water temperature + turbidity
Both models do a poor job of predicting chlorophyll-a

-----------------------------
Week 10 & 11, Apr 17, 2019
R Script: Week10_11_WWoelmer.R
input data file: BVR_CTD.csv
Description
Part 1: developed a generalized linear model to test the drivers of chlorophylla in Beaverdam Reservoir.
Driver variables tested include water temperature, depth, and turbidity. turbidity was a significant positive driver of surface (0.1m depth) chlorophyll
Part 2: used a likelihood ratio test and AIC to test the significance of several generalized linear models. Both tests confirmed that no model combinations were significant. 

---------------------------------
Week 12, Apr 23, 2019
R Script: Week12_WWoelmer.R
input data file: BVR_CTD.csv
Description:
This week I developed a mixed effects model for chlorophyll-a concentrations in Beaverdam Reservoir. To control for the effect of season on changes in chla concentrations, I created a 'month' factor that was included as a random effect in my mixed effects model. I used two fixed effects, turbidity and water temperature. Both fixed effects have significant positive effects on chla. 